baseURL = "https://www.paretooptimal.dev"
languageCode = "en-us"
title = "Pareto Optimal Dev"
theme = "cortex"
canonifyURLs = true
relativeUrls = true
staticDir = ["static", "org/data"]

[params]
email = "pareto.optimal@mailfence.com"
sourceRepoURL = "https://github.com/ParetoOptimalDev/ParetoOptimalDev.github.io/"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "tango"
    tabWidth = 4

[permalinks]
  posts = "/:title/"
